import { User, Destination, VehicleCategory, Vehicle, Vendor, Booking, Review } from './types';

// Mock Users
export const mockUsers: User[] = [
  {
    id: 1,
    name: 'Budi Santoso',
    email: 'budi@gmail.com',
    phone: '08123456789',
    role: 'CUSTOMER',
    createdAt: '2026-01-15T08:00:00Z',
  },
  {
    id: 2,
    name: 'Dewi Lestari',
    email: 'dewi@gmail.com',
    phone: '08234567890',
    role: 'VENDOR',
    createdAt: '2026-01-20T09:00:00Z',
  },
  {
    id: 3,
    name: 'Admin Travelink',
    email: 'admin@travelink.com',
    phone: '08345678901',
    role: 'ADMIN',
    createdAt: '2026-01-01T07:00:00Z',
  },
];

// Mock Vehicle Categories
export const mockVehicleCategories: VehicleCategory[] = [
  { id: 1, name: 'Jeep', slug: 'jeep', icon: 'https://images.pexels.com/photos/12065618/pexels-photo-12065618.jpeg?auto=compress&cs=tinysrgb&w=100' },
  { id: 2, name: 'ATV', slug: 'atv', icon: 'https://images.pexels.com/photos/162421/mercedes-benz-auto-vehicle-mercedes-benz-gl-162421.jpeg?auto=compress&cs=tinysrgb&w=100' },
  { id: 3, name: 'Jetski', slug: 'jetski', icon: 'https://images.pexels.com/photos/163117/straw-sailboat-vehicle-water-163117.jpeg?auto=compress&cs=tinysrgb&w=100' },
  { id: 4, name: 'Motor', slug: 'motor', icon: 'https://images.pexels.com/photos/163117/straw-sailboat-vehicle-water-163117.jpeg?auto=compress&cs=tinysrgb&w=100' },
  { id: 5, name: 'Sepeda', slug: 'sepeda', icon: 'https://images.pexels.com/photos/163117/straw-sailboat-vehicle-water-163117.jpeg?auto=compress&cs=tinysrgb&w=100' },
];

// Mock Destinations
export const mockDestinations: Destination[] = [
  {
    id: 1,
    name: 'Pantai Kuta',
    slug: 'pantai-kuta',
    type: 'BEACH',
    city: 'Bali',
    image: 'https://images.pexels.com/photos/1450353/pexels-photo-1450353.jpeg?auto=compress&cs=tinysrgb&w=800',
    isActive: true,
    createdAt: '2026-01-10T10:00:00Z',
  },
  {
    id: 2,
    name: 'Gunung Bromo',
    slug: 'gunung-bromo',
    type: 'MOUNTAIN',
    city: 'Jawa Timur',
    image: 'https://images.pexels.com/photos/1450353/pexels-photo-1450353.jpeg?auto=compress&cs=tinysrgb&w=800',
    isActive: true,
    createdAt: '2026-01-11T11:00:00Z',
  },
  {
    id: 3,
    name: 'Raja Ampat',
    slug: 'raja-ampat',
    type: 'ISLAND',
    city: 'Papua Barat',
    image: 'https://images.pexels.com/photos/1450353/pexels-photo-1450353.jpeg?auto=compress&cs=tinysrgb&w=800',
    isActive: true,
    createdAt: '2026-01-12T12:00:00Z',
  },
  {
    id: 4,
    name: 'Danau Toba',
    slug: 'danau-toba',
    type: 'LAKE',
    city: 'Sumatera Utara',
    image: 'https://images.pexels.com/photos/1450353/pexels-photo-1450353.jpeg?auto=compress&cs=tinysrgb&w=800',
    isActive: true,
    createdAt: '2026-01-13T13:00:00Z',
  },
  {
    id: 5,
    name: 'Taman Nasional Komodo',
    slug: 'taman-nasional-komodo',
    type: 'FOREST',
    city: 'NTT',
    image: 'https://images.pexels.com/photos/1450353/pexels-photo-1450353.jpeg?auto=compress&cs=tinysrgb&w=800',
    isActive: true,
    createdAt: '2026-01-14T14:00:00Z',
  },
  {
    id: 6,
    name: 'Candi Borobudur',
    slug: 'candi-borobudur',
    type: 'TEMPLE',
    city: 'Jawa Tengah',
    image: 'https://images.pexels.com/photos/1450353/pexels-photo-1450353.jpeg?auto=compress&cs=tinysrgb&w=800',
    isActive: true,
    createdAt: '2026-01-15T15:00:00Z',
  },
];

// Mock Vendors
export const mockVendors: Vendor[] = [
  {
    id: 1,
    userId: 2,
    businessName: 'Bali Adventure Tours',
    address: 'Jl. Raya Kuta No. 10',
    city: 'Bali',
    bankName: 'BCA',
    bankAccount: '1234567890',
    isVerified: true,
    createdAt: '2026-01-20T09:00:00Z',
  },
  {
    id: 2,
    userId: 4,
    businessName: 'Bromo Explorer',
    address: 'Jl. Bromo No. 5',
    city: 'Jawa Timur',
    bankName: 'Mandiri',
    bankAccount: '0987654321',
    isVerified: true,
    createdAt: '2026-01-21T10:00:00Z',
  },
  {
    id: 3,
    userId: 5,
    businessName: 'Raja Ampat Dive Center',
    address: 'Jl. Waisai No. 15',
    city: 'Papua Barat',
    bankName: 'BNI',
    bankAccount: '1122334455',
    isVerified: false,
    createdAt: '2026-01-22T11:00:00Z',
  },
];

// Mock Vehicles
export const mockVehicles: Vehicle[] = [
  {
    id: 1,
    name: 'Jeep Wrangler 2022',
    description: 'Jeep tangguh cocok untuk medan off-road di sekitar Bromo. Dilengkapi dengan AC dan audio system.',
    capacity: 4,
    pricePerDay: 350000,
    status: 'ACTIVE',
    vendorId: 1,
    categoryId: 1,
    destinationId: 1,
    category: mockVehicleCategories[0],
    destination: mockDestinations[0],
    vendor: mockVendors[0],
    createdAt: '2026-01-20T10:00:00Z',
  },
  {
    id: 2,
    name: 'ATV 250cc',
    description: 'ATV powerful untuk petualangan seru di pantai atau gunung.',
    capacity: 1,
    pricePerDay: 150000,
    status: 'ACTIVE',
    vendorId: 1,
    categoryId: 2,
    destinationId: 2,
    category: mockVehicleCategories[1],
    destination: mockDestinations[1],
    vendor: mockVendors[0],
    createdAt: '2026-01-21T11:00:00Z',
  },
  {
    id: 3,
    name: 'Jetski Yamaha',
    description: 'Jetski cepat untuk sensasi bermain air di pantai Kuta.',
    capacity: 2,
    pricePerDay: 500000,
    status: 'ACTIVE',
    vendorId: 1,
    categoryId: 3,
    destinationId: 1,
    category: mockVehicleCategories[2],
    destination: mockDestinations[0],
    vendor: mockVendors[0],
    createdAt: '2026-01-22T12:00:00Z',
  },
  {
    id: 4,
    name: 'Honda CRF 250',
    description: 'Motor trail untuk eksplorasi medan sulit.',
    capacity: 1,
    pricePerDay: 200000,
    status: 'ACTIVE',
    vendorId: 2,
    categoryId: 4,
    destinationId: 2,
    category: mockVehicleCategories[3],
    destination: mockDestinations[1],
    vendor: mockVendors[1],
    createdAt: '2026-01-23T13:00:00Z',
  },
  {
    id: 5,
    name: 'Sepeda Gunung Polygon',
    description: 'Sepeda gunung berkualitas untuk trekking di Raja Ampat.',
    capacity: 1,
    pricePerDay: 75000,
    status: 'ACTIVE',
    vendorId: 2,
    categoryId: 5,
    destinationId: 3,
    category: mockVehicleCategories[4],
    destination: mockDestinations[2],
    vendor: mockVendors[1],
    createdAt: '2026-01-24T14:00:00Z',
  },
  {
    id: 6,
    name: 'Jeep CJ7 Classic',
    description: 'Jeep klasik untuk tur wisata vintage di sekitar Borobudur.',
    capacity: 5,
    pricePerDay: 450000,
    status: 'ACTIVE',
    vendorId: 3,
    categoryId: 1,
    destinationId: 6,
    category: mockVehicleCategories[0],
    destination: mockDestinations[5],
    vendor: mockVendors[2],
    createdAt: '2026-01-25T15:00:00Z',
  },
];

// Mock Bookings
export const mockBookings: Booking[] = [
  {
    id: 1,
    vehicleId: 1,
    userId: 1,
    startDate: '2026-06-01',
    endDate: '2026-06-03',
    totalPrice: 1050000,
    status: 'CONFIRMED',
    notes: 'Tolong siapkan helm ekstra',
    vehicle: mockVehicles[0],
    user: mockUsers[0],
    createdAt: '2026-01-25T08:00:00Z',
  },
  {
    id: 2,
    vehicleId: 2,
    userId: 1,
    startDate: '2026-06-05',
    endDate: '2026-06-05',
    totalPrice: 150000,
    status: 'COMPLETED',
    vehicle: mockVehicles[1],
    user: mockUsers[0],
    createdAt: '2026-01-26T09:00:00Z',
  },
  {
    id: 3,
    vehicleId: 3,
    userId: 1,
    startDate: '2026-06-10',
    endDate: '2026-06-10',
    totalPrice: 500000,
    status: 'PENDING',
    notes: 'Pagi hari sebelum jam 10',
    vehicle: mockVehicles[2],
    user: mockUsers[0],
    createdAt: '2026-01-27T10:00:00Z',
  },
];

// Mock Reviews
export const mockReviews: Review[] = [
  {
    id: 1,
    bookingId: 2,
    rating: 5,
    comment: 'Kendaraannya sangat nyaman dan bersih! Pelayanan prima.',
    user: mockUsers[0],
    vehicle: mockVehicles[1],
    createdAt: '2026-01-26T14:00:00Z',
  },
  {
    id: 2,
    bookingId: 1,
    rating: 4,
    comment: 'Jeepnya keren banget, cocok untuk off-road. Recommended!',
    user: mockUsers[0],
    vehicle: mockVehicles[0],
    createdAt: '2026-01-25T18:00:00Z',
  },
];

// Destination type labels
export const destinationTypeLabels: Record<string, string> = {
  BEACH: 'Pantai',
  MOUNTAIN: 'Gunung',
  CITY: 'Kota',
  FOREST: 'Hutan',
  ISLAND: 'Pulau',
  WATERFALL: 'Air Terjun',
  TEMPLE: 'Candi',
  LAKE: 'Danau',
  OTHER: 'Lainnya',
};

// Booking status labels and colors
export const bookingStatusConfig: Record<string, { label: string; color: string }> = {
  PENDING: { label: 'Menunggu', color: 'bg-yellow-100 text-yellow-800 border-yellow-200' },
  CONFIRMED: { label: 'Dikonfirmasi', color: 'bg-blue-100 text-blue-800 border-blue-200' },
  PAID: { label: 'Sudah Dibayar', color: 'bg-green-100 text-green-800 border-green-200' },
  COMPLETED: { label: 'Selesai', color: 'bg-sky-100 text-sky-800 border-sky-200' },
  CANCELLED: { label: 'Dibatalkan', color: 'bg-red-100 text-red-800 border-red-200' },
};
